/**
 * Points `src/lib/version.ts` at the latest published GitHub release.
 *
 * Run as the first step of `bun run build`, so the version in the header is
 * whatever people can actually download rather than whatever was last typed
 * into a constant.
 *
 * Two deliberate properties:
 *
 * - **It never fails the build.** A rate-limited, offline or misbehaving API
 *   leaves the committed value in place and prints a warning. A marketing page
 *   that will not deploy because GitHub is having a bad morning is a worse
 *   outcome than a version string one release behind.
 * - **It writes a source file that is committed.** That file is the offline
 *   fallback, and a build that moves it shows up in `git status`, so the bump
 *   is visible rather than silent.
 */
import { readFile, writeFile } from "node:fs/promises"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const REPO = "Bramgus12/container-gui"
const API = `https://api.github.com/repos/${REPO}/releases/latest`
const TIMEOUT_MS = 10_000

/**
 * Semver, with the tag's conventional leading `v` optional. The result is
 * interpolated into a TypeScript string literal, so anything that is not
 * plainly a version number is rejected rather than written to disk.
 */
const TAG = /^v?(\d+\.\d+\.\d+)$/

const target = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "src",
  "lib",
  "version.ts"
)

function render(version: string) {
  return `// Generated by scripts/fetch-version.ts during \`bun run build\`.
// Committed so the build still works offline: when the GitHub API cannot be
// reached, this value is what the site ships. Safe to edit by hand.
export const APP_VERSION = "${version}"
`
}

function warn(reason: string) {
  console.warn(`fetch-version: ${reason} — keeping the committed version.`)
}

async function latestRelease(): Promise<string | undefined> {
  const headers: Record<string, string> = {
    accept: "application/vnd.github+json",
    "user-agent": `${REPO} website build`,
  }

  // Vercel and GitHub Actions both expose a token; using it lifts the
  // unauthenticated 60-requests-per-hour limit that a busy build could hit.
  const token = process.env.GITHUB_TOKEN ?? process.env.GH_TOKEN
  if (token) headers.authorization = `Bearer ${token}`

  const response = await fetch(API, {
    headers,
    signal: AbortSignal.timeout(TIMEOUT_MS),
  })

  if (!response.ok) {
    warn(`GitHub responded ${response.status}`)
    return undefined
  }

  const body = (await response.json()) as { tag_name?: unknown }
  if (typeof body.tag_name !== "string") {
    warn("the response had no tag_name")
    return undefined
  }

  const match = TAG.exec(body.tag_name.trim())
  if (!match) {
    warn(`tag "${body.tag_name}" is not a plain semver tag`)
    return undefined
  }

  return match[1]
}

let version: string | undefined
try {
  version = await latestRelease()
} catch (error) {
  warn(error instanceof Error ? error.message : String(error))
}

if (version) {
  const next = render(version)
  const current = await readFile(target, "utf8").catch(() => "")

  if (current === next) {
    console.log(`fetch-version: already at ${version}`)
  } else {
    await writeFile(target, next)
    console.log(`fetch-version: updated to ${version}`)
  }
}
