// Generated by scripts/fetch-version.ts during `bun run build`.
// Committed so the build still works offline: when the GitHub API cannot be
// reached, this value is what the site ships. Safe to edit by hand.
export const APP_VERSION = "1.5.0"
